"""
Snappi-based FCS (Frame Check Sequence) error handling tests.

Implements the test plan documented in
``docs/testplan/snappi/switch-fcs-tests.md``:

* Test Case 1 - Line-rate FCS-error traffic test (:func:`test_fcs_line_rate_drop`)
    Validates that the DUT drops 100% of ingress frames carrying an FCS error
    while transmitting at line rate.

* Test Case 2 - FCS-error isolation test (:func:`test_fcs_error_isolation`)
    Validates that valid (good-FCS) traffic is unaffected by the presence of
    bad-FCS traffic transmitted on parallel links to the same receive port.

The tests run on the ``nut-single-dut`` NUT topology (see
``docs/testbed/README.testbed.NUT.md``). Bad-FCS frames are generated by
setting the traffic-item CRC mode to ``badCrc`` in IxNetwork, mirroring the
low-level IxNetwork access pattern used by ``test_fec_error_insertion.py``.
"""
from tests.snappi_tests.dataplane.imports import (        # noqa: F401
    pytest, SnappiTestParams, wait, wait_for_arp, pytest_assert,
)
from snappi_tests.dataplane.files.helper import (         # noqa: F401
    get_duthost_bgp_details, create_snappi_config, set_primary_chassis,
    create_traffic_items, start_stop, get_stats,
)
from tests.common.telemetry import GaugeMetric, UNIT_PERCENT
import logging

pytestmark = [pytest.mark.topology("nut")]
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Metric names / labels (see section 5 of the test plan). Kept local to this
# module until promoted into test_reporting/telemetry/metric_definitions.py.
# ---------------------------------------------------------------------------
METRIC_NAME_TG_TX_GOOD_UTIL = "tg.tx.good.util"
METRIC_NAME_TG_RX_GOOD_UTIL = "tg.rx.good.util"
METRIC_NAME_TG_TX_BAD_UTIL = "tg.tx.bad.util"
METRIC_NAME_TG_RX_BAD_UTIL = "tg.rx.bad.util"
METRIC_LABEL_TG_FCS_ERROR_TYPE = "tg.fcs_error_type"
METRIC_LABEL_TG_FRAME_BYTES = "tg.frame_bytes"
METRIC_LABEL_TG_IP_VERSION = "tg.ip_version"

GOOD_FLOW = "FCS-Good-Flow"
BAD_FLOW = "FCS-Bad-Flow"

# The test plan calls for a 60s transmission window; a shorter default keeps the
# scaffold runnable. Override via the ``test_duration_sec`` parametrization.
DEFAULT_TEST_DURATION_SEC = 10

# Good-FCS traffic must not lose more than this fraction (percent) of frames.
GOOD_FLOW_MAX_LOSS_PCT = 1.0


def _set_flow_crc(snappi_api, flow_name, crc_mode="badCrc"):
    """Force the CRC generation mode of a traffic item via IxNetwork.

    snappi (OTG) does not expose a native bad-CRC knob, so we reach into the
    underlying IxNetwork session and set ``ConfigElement.Crc`` on the matching
    traffic item. Valid ``crc_mode`` values are ``goodCrc`` and ``badCrc``.
    """
    ixnet = snappi_api._ixnetwork
    traffic_item = ixnet.Traffic.TrafficItem.find(Name=flow_name)
    pytest_assert(len(traffic_item) > 0, "Traffic item '{}' not found in IxNetwork".format(flow_name))
    for config_element in traffic_item.ConfigElement.find():
        config_element.Crc = crc_mode
    logger.info("Set CRC mode of flow '%s' to '%s'", flow_name, crc_mode)


def _dut_rx_error_count(tx_ports):
    """Sum the RX error counters of the DUT ports facing the given TG TX ports.

    Bad-FCS frames are dropped at the DUT ingress port connected to the TG TX
    port, so their RX_ERR counter is where the errors accumulate.
    """
    total = 0
    seen = set()
    for port in tx_ports:
        duthost = port["duthost"]
        peer_port = port["peer_port"]
        key = (duthost.hostname, peer_port)
        if key in seen:
            continue
        seen.add(key)
        try:
            rows = duthost.show_and_parse("show interfaces counters -i {}".format(peer_port))
        except Exception as exc:   # best-effort: counter format varies across platforms
            logger.warning("Could not read counters for %s/%s: %s", duthost.hostname, peer_port, exc)
            continue
        for row in rows:
            rx_err = row.get("rx_err", "0") or "0"
            try:
                total += int(str(rx_err).replace(",", ""))
            except ValueError:
                continue
    return total


def _flow_stats_by_name(snappi_api):
    """Return a ``{flow_name: flow_metric}`` map from Traffic Item Statistics."""
    return {stat.name: stat for stat in get_stats(snappi_api, "Traffic Item Statistics")}


def _rx_util_pct(flow_stat):
    """Best-effort RX utilization (percent) relative to the flow's TX rate."""
    tx_rate = float(getattr(flow_stat, "frames_tx_rate", 0) or 0)
    rx_rate = float(getattr(flow_stat, "frames_rx_rate", 0) or 0)
    if tx_rate <= 0:
        return 0.0
    return round(min(rx_rate / tx_rate, 1.0) * 100.0, 2)


def _report_metrics(db_reporter, flows, ip_version, frame_size, fcs_error_type, line_rate):
    """Record the good/bad TX/RX utilization metrics from section 5 of the plan."""
    labels = {
        METRIC_LABEL_TG_IP_VERSION: ip_version,
        METRIC_LABEL_TG_FRAME_BYTES: frame_size,
        METRIC_LABEL_TG_FCS_ERROR_TYPE: fcs_error_type,
    }

    def _record(name, description, value):
        GaugeMetric(name, description, UNIT_PERCENT, db_reporter).record(value, labels)

    if BAD_FLOW in flows:
        _record(METRIC_NAME_TG_TX_BAD_UTIL, "TX utilization of bad-FCS traffic", float(line_rate))
        _record(METRIC_NAME_TG_RX_BAD_UTIL, "RX utilization of bad-FCS traffic", _rx_util_pct(flows[BAD_FLOW]))
    if GOOD_FLOW in flows:
        _record(METRIC_NAME_TG_TX_GOOD_UTIL, "TX utilization of good-FCS traffic", float(line_rate))
        _record(METRIC_NAME_TG_RX_GOOD_UTIL, "RX utilization of good-FCS traffic", _rx_util_pct(flows[GOOD_FLOW]))
    db_reporter.report()


def _build_flow(snappi_obj_handles, flow_name, tx_role, rx_role, frame_size, line_rate, tx_slice=None):
    """Assemble a single ``traffic_flow_config`` entry for :func:`create_traffic_items`."""
    tx_names = snappi_obj_handles[tx_role]["ip"]
    if tx_slice is not None:
        tx_names = tx_names[tx_slice]
    return {
        "flow_name": flow_name,
        "tx_names": tx_names,
        "rx_names": snappi_obj_handles[rx_role]["ip"],
        "frame_size": frame_size,
        "line_rate": line_rate,
        # No duration key => continuous transmission, stopped explicitly after test_duration_sec.
        "is_rdma": False,
    }


def _start_and_measure(snappi_api, snappi_config, test_duration_sec):
    """Start protocols + traffic, hold for ``test_duration_sec``, then stop and collect stats."""
    snappi_api.set_config(snappi_config)
    start_stop(snappi_api, operation="start", op_type="protocols")
    logger.info("Waiting for ARP/ND to resolve ...")
    wait_for_arp(snappi_api, max_attempts=30, poll_interval_sec=2)
    start_stop(snappi_api, operation="start", op_type="traffic")
    wait(test_duration_sec, "For FCS traffic transmission")
    get_stats(snappi_api, "Traffic Item Statistics", return_type="print")
    flows = _flow_stats_by_name(snappi_api)
    start_stop(snappi_api, operation="stop", op_type="traffic")
    return flows


@pytest.mark.parametrize("ip_version", ["IPv4", "IPv6"])
@pytest.mark.parametrize("fcs_error_type", ["zero", "random"])
@pytest.mark.parametrize("frame_size", [128, 1518])
@pytest.mark.parametrize("tx_port_count", [1])
@pytest.mark.parametrize("test_duration_sec", [DEFAULT_TEST_DURATION_SEC])
def test_fcs_line_rate_drop(
    duthosts,
    snappi_api,
    get_snappi_ports,
    fanout_graph_facts_multidut,
    set_primary_chassis,    # noqa: F811
    create_snappi_config,   # noqa: F811
    db_reporter,
    tbinfo,
    ip_version,
    fcs_error_type,
    frame_size,
    tx_port_count,
    test_duration_sec,
):
    """Line-rate FCS-error traffic test (test plan case 1).

    Transmit 100%-line-rate traffic composed entirely of FCS-error frames and
    assert that the DUT drops all of it: the TG RX port receives 0 frames and
    the DUT ingress RX_ERR counter increments.
    """
    ports = get_duthost_bgp_details(duthosts, get_snappi_ports, ip_version)
    pytest_assert(
        len(ports) >= tx_port_count + 1,
        "Need at least {} TG ports, found {}".format(tx_port_count + 1, len(ports)),
    )
    tx_ports = ports[:tx_port_count]
    rx_ports = [ports[tx_port_count]]

    snappi_extra_params = SnappiTestParams()
    snappi_extra_params.protocol_config = {
        "Tx": {"protocol_type": "bgp", "ports": tx_ports, "subnet_type": ip_version, "is_rdma": False},
        "Rx": {"protocol_type": "bgp", "ports": rx_ports, "subnet_type": ip_version, "is_rdma": False},
    }
    snappi_config, snappi_obj_handles = create_snappi_config(snappi_extra_params)

    snappi_extra_params.traffic_flow_config = [
        _build_flow(snappi_obj_handles, BAD_FLOW, "Tx", "Rx", frame_size, 100),
    ]
    snappi_config = create_traffic_items(snappi_config, snappi_extra_params)
    snappi_api.set_config(snappi_config)
    _set_flow_crc(snappi_api, BAD_FLOW, crc_mode="badCrc")

    rx_err_before = _dut_rx_error_count(tx_ports)
    flows = _start_and_measure(snappi_api, snappi_config, test_duration_sec)
    rx_err_after = _dut_rx_error_count(tx_ports)

    bad = flows[BAD_FLOW]
    pytest_assert(int(bad.frames_tx) > 0, "No bad-FCS frames were transmitted")
    pytest_assert(
        int(bad.frames_rx) == 0,
        "DUT forwarded {} FCS-error frames; expected 0".format(bad.frames_rx),
    )
    pytest_assert(
        rx_err_after > rx_err_before,
        "DUT RX_ERR counter did not increase (before={}, after={})".format(rx_err_before, rx_err_after),
    )
    logger.info("PASS: All FCS-error frames dropped; DUT RX_ERR delta=%d", rx_err_after - rx_err_before)

    _report_metrics(db_reporter, flows, ip_version, frame_size, fcs_error_type, line_rate=100)


@pytest.mark.parametrize("ip_version", ["IPv4", "IPv6"])
@pytest.mark.parametrize("fcs_error_type", ["zero", "random"])
@pytest.mark.parametrize("frame_size", [128, 1518])
@pytest.mark.parametrize("tx_port_count", [1])
@pytest.mark.parametrize("test_duration_sec", [DEFAULT_TEST_DURATION_SEC])
def test_fcs_error_isolation(
    duthosts,
    snappi_api,
    get_snappi_ports,
    fanout_graph_facts_multidut,
    set_primary_chassis,    # noqa: F811
    create_snappi_config,   # noqa: F811
    db_reporter,
    tbinfo,
    ip_version,
    fcs_error_type,
    frame_size,
    tx_port_count,
    test_duration_sec,
):
    """FCS-error isolation test, 1-to-1 parallel links (test plan case 2).

    Interleave bad-FCS and good-FCS traffic across parallel TX ports feeding the
    same RX port(s). Assert that good-FCS traffic is delivered while every
    bad-FCS frame is dropped at the DUT ingress.
    """
    ports = get_duthost_bgp_details(duthosts, get_snappi_ports, ip_version)
    needed = 3 * tx_port_count
    pytest_assert(
        len(ports) >= needed,
        "Need at least {} TG ports for isolation test, found {}".format(needed, len(ports)),
    )
    tx_ports = ports[: 2 * tx_port_count]
    rx_ports = ports[2 * tx_port_count: 3 * tx_port_count]

    snappi_extra_params = SnappiTestParams()
    snappi_extra_params.protocol_config = {
        "Tx": {"protocol_type": "bgp", "ports": tx_ports, "subnet_type": ip_version, "is_rdma": False},
        "Rx": {"protocol_type": "bgp", "ports": rx_ports, "subnet_type": ip_version, "is_rdma": False},
    }
    snappi_config, snappi_obj_handles = create_snappi_config(snappi_extra_params)

    # Even TX ports -> bad-FCS, odd TX ports -> good-FCS (each at 50% line rate).
    snappi_extra_params.traffic_flow_config = [
        _build_flow(snappi_obj_handles, BAD_FLOW, "Tx", "Rx", frame_size, 50, tx_slice=slice(0, None, 2)),
        _build_flow(snappi_obj_handles, GOOD_FLOW, "Tx", "Rx", frame_size, 50, tx_slice=slice(1, None, 2)),
    ]
    snappi_config = create_traffic_items(snappi_config, snappi_extra_params)
    snappi_api.set_config(snappi_config)
    _set_flow_crc(snappi_api, BAD_FLOW, crc_mode="badCrc")
    _set_flow_crc(snappi_api, GOOD_FLOW, crc_mode="goodCrc")

    bad_tx_ports = tx_ports[0::2]
    rx_err_before = _dut_rx_error_count(bad_tx_ports)
    flows = _start_and_measure(snappi_api, snappi_config, test_duration_sec)
    rx_err_after = _dut_rx_error_count(bad_tx_ports)

    bad = flows[BAD_FLOW]
    good = flows[GOOD_FLOW]
    good_loss = float(good.loss or 0)
    pytest_assert(
        int(bad.frames_rx) == 0,
        "RX port received {} bad-FCS frames; expected 0".format(bad.frames_rx),
    )
    pytest_assert(int(good.frames_rx) > 0, "No good-FCS frames were delivered")
    pytest_assert(
        good_loss <= GOOD_FLOW_MAX_LOSS_PCT,
        "Good-FCS traffic loss {}% exceeds {}% threshold".format(good_loss, GOOD_FLOW_MAX_LOSS_PCT),
    )
    pytest_assert(
        rx_err_after > rx_err_before,
        "DUT RX_ERR counter did not increase (before={}, after={})".format(rx_err_before, rx_err_after),
    )
    logger.info(
        "PASS: good-FCS delivered (loss=%.3f%%), bad-FCS isolated; DUT RX_ERR delta=%d",
        good_loss, rx_err_after - rx_err_before,
    )

    _report_metrics(db_reporter, flows, ip_version, frame_size, fcs_error_type, line_rate=50)
